from django.urls import path

from .views import (
    AssistantConversationListCreateView,
    AssistantConversationMessageListCreateView,
    AdminCommunityPostDetailView,
    AdminCommunityPostListCreateView,
    AdminCourseDetailView,
    AdminCourseListCreateView,
    AdminDuaListView,
    AdminEpisodeDetailView,
    AdminEpisodeListCreateView,
    AdminAnalyticsListView,
    AdminOverviewView,
    AdminReflectionListView,
    AdminResourceDetailView,
    AdminResourceListCreateView,
    AdminUserListView,
    CommunityCategoryListView,
    CommunityPostAttachmentListCreateView,
    CommunityPostBookmarkToggleView,
    CommunityPostLikeToggleView,
    CommunityPostListCreateView,
    CommunityReplyListCreateView,
    CourseEnrollmentToggleView,
    CourseListView,
    DailyAyahView,
    DashboardSummaryView,
    DuaAmeenToggleView,
    DuaRequestListCreateView,
    FeaturedCourseView,
    FollowGraphView,
    FollowToggleView,
    HealthCheckView,
    KnowledgeCategoryListView,
    KnowledgeResourceListView,
    LoginView,
    LogoutView,
    LessonCompletionToggleView,
    ModerationReportDetailView,
    ModerationReportListCreateView,
    NotificationListView,
    NotificationMarkReadView,
    PodcastEpisodeListView,
    PrayerTimesView,
    ReflectionDetailView,
    ReflectionListCreateView,
    RegisterView,
    SavedResourceListView,
    SavedResourceToggleView,
    SharedContentListCreateView,
    UserMeView,
    UserSharedContentListView,
    AnalyticsEventCreateView,
)

urlpatterns = [
    path("health", HealthCheckView.as_view(), name="health"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/register", RegisterView.as_view(), name="auth-register"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("auth/me", UserMeView.as_view(), name="auth-me"),
    path("social/follows", FollowGraphView.as_view(), name="follow-graph"),
    path("social/users/<int:user_id>/follow", FollowToggleView.as_view(), name="follow-toggle"),
    path("dashboard/summary", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("data/daily-ayah", DailyAyahView.as_view(), name="daily-ayah"),
    path("reflections", ReflectionListCreateView.as_view(), name="reflection-list-create"),
    path("reflections/<int:pk>", ReflectionDetailView.as_view(), name="reflection-detail"),
    path("duas", DuaRequestListCreateView.as_view(), name="dua-list-create"),
    path("duas/<int:pk>/ameen", DuaAmeenToggleView.as_view(), name="dua-ameen"),
    path("community/categories", CommunityCategoryListView.as_view(), name="community-categories"),
    path("community/posts", CommunityPostListCreateView.as_view(), name="community-posts"),
    path(
        "community/posts/<int:pk>/attachments",
        CommunityPostAttachmentListCreateView.as_view(),
        name="community-post-attachments",
    ),
    path("community/posts/<int:pk>/replies", CommunityReplyListCreateView.as_view(), name="community-post-replies"),
    path("community/posts/<int:pk>/like", CommunityPostLikeToggleView.as_view(), name="community-post-like"),
    path("community/posts/<int:pk>/bookmark", CommunityPostBookmarkToggleView.as_view(), name="community-post-bookmark"),
    path("courses", CourseListView.as_view(), name="course-list"),
    path("courses/featured", FeaturedCourseView.as_view(), name="course-featured"),
    path("courses/<slug:slug>/enroll", CourseEnrollmentToggleView.as_view(), name="course-enroll"),
    path("courses/lessons/<int:lesson_id>/complete", LessonCompletionToggleView.as_view(), name="lesson-complete"),
    path("resources/categories", KnowledgeCategoryListView.as_view(), name="resource-categories"),
    path("resources", KnowledgeResourceListView.as_view(), name="resource-list"),
    path("resources/saved", SavedResourceListView.as_view(), name="saved-resource-list"),
    path("resources/<int:resource_id>/save", SavedResourceToggleView.as_view(), name="saved-resource-toggle"),
    path("shared-content", SharedContentListCreateView.as_view(), name="shared-content"),
    path("shared-content/mine", UserSharedContentListView.as_view(), name="shared-content-mine"),
    path("audio/episodes", PodcastEpisodeListView.as_view(), name="podcast-list"),
    path("prayer/today", PrayerTimesView.as_view(), name="prayer-times"),
    path("notifications", NotificationListView.as_view(), name="notification-list"),
    path("notifications/<int:pk>/read", NotificationMarkReadView.as_view(), name="notification-read"),
    path("moderation/reports", ModerationReportListCreateView.as_view(), name="moderation-reports"),
    path("moderation/reports/<int:pk>", ModerationReportDetailView.as_view(), name="moderation-report-detail"),
    path("analytics/events", AnalyticsEventCreateView.as_view(), name="analytics-events"),
    path("assistant/conversations", AssistantConversationListCreateView.as_view(), name="assistant-conversations"),
    path(
        "assistant/conversations/<int:pk>/messages",
        AssistantConversationMessageListCreateView.as_view(),
        name="assistant-conversation-messages",
    ),
    path("admin/overview", AdminOverviewView.as_view(), name="admin-overview"),
    path("admin/users", AdminUserListView.as_view(), name="admin-users"),
    path("admin/reflections", AdminReflectionListView.as_view(), name="admin-reflections"),
    path("admin/duas", AdminDuaListView.as_view(), name="admin-duas"),
    path("admin/analytics", AdminAnalyticsListView.as_view(), name="admin-analytics"),
    path("admin/courses", AdminCourseListCreateView.as_view(), name="admin-courses"),
    path("admin/courses/<int:pk>", AdminCourseDetailView.as_view(), name="admin-course-detail"),
    path("admin/resources", AdminResourceListCreateView.as_view(), name="admin-resources"),
    path("admin/resources/<int:pk>", AdminResourceDetailView.as_view(), name="admin-resource-detail"),
    path("admin/episodes", AdminEpisodeListCreateView.as_view(), name="admin-episodes"),
    path("admin/episodes/<int:pk>", AdminEpisodeDetailView.as_view(), name="admin-episode-detail"),
    path("admin/community-posts", AdminCommunityPostListCreateView.as_view(), name="admin-community-posts"),
    path("admin/community-posts/<int:pk>", AdminCommunityPostDetailView.as_view(), name="admin-community-post-detail"),
]
